# Generated by Django 3.2.4 on 2021-06-14 13:59

import bikes.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_type', models.CharField(help_text='Enter a bike type (mtb, road, gravel etc)', max_length=50, unique=True, verbose_name='Bike type')),
            ],
            options={
                'ordering': ['bike_type'],
            },
        ),
        migrations.CreateModel(
            name='Cyklo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=bikes.models.picture_path, verbose_name='Picture')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('release_date', models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Release date')),
                ('rate', models.FloatField(default=5.0, help_text='Please enter an float value (range 1.0 -10.0)', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Rate')),
                ('type', models.ManyToManyField(help_text='Select a type for this bike', to='bikes.Type')),
            ],
            options={
                'ordering': ['-release_date', 'name'],
            },
        ),
    ]
